# Generated by Django 2.2 on 2022-03-13 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=400)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(default=500)),
                ('discount_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(null=True, upload_to='product_imgs/')),
                ('label', models.CharField(blank=True, choices=[('b', 'blue'), ('r', 'red')], max_length=2, null=True)),
                ('label_text', models.CharField(blank=True, max_length=10, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Categories')),
            ],
            options={
                'verbose_name_plural': '5. Products',
            },
        ),
    ]
