# Generated by Django 2.2 on 2022-03-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220318_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('b', 'primary'), ('r', 'danger'), ('y', 'warning')], max_length=2, null=True),
        ),
    ]
