# Generated by Django 2.2 on 2022-03-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220324_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='Brands/')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': '.3 Brand',
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': '.4 Products'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': '.6 Order'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': '.5 orderd Items'},
        ),
    ]
